### PR TITLE
Add Serbian translation

### PR DESCRIPTION
**Pull request by pejakm**
Please allow localization of `app_name `, for Serbian at least.

### CODE REVIEW

**Comment by casimir** [comment]
```app_name``` would change to what?

**Comment by pejakm** [comment]
I meant on allowing localization of app name (remove `translatable="false"` from `app_name` string). In Serbian at least, we tend to localize application name, too, because it isn't appealing if you use localized application (Cyrillic script) but its name is left in English.

**Comment by casimir** [comment]
Does the "translate all the things" applies to logo too? If so I guess the Play Store description will need a translation too. By any chance would you mind translate it if I set up the files in the source tree?

**Comment by pejakm** [comment]
No, not the logo, although in KDE there are some images which have localized versions.

Translating Play store descriptions is not imperative, but if the author provides this possibility we translate it. So, yes, I'll translate, thanks.

More about name localization: if the name of a program is a trademark, then in Serbian we only transcribe the name, eg. Firefox -> Фајерфокс (Cyrillic script, which is default)/Fajerfoks (Latin script).

**Comment by pejakm** [comment]
And, to conclude: there are Android apps which don't have localized names. If I'm the translator I always raise a questions of this. Some authors accept this, some don't. I don't wanna make pressure on anyone, I simply explain that (at least) in Serbian we used to have localized name (because of Cyrillic script) and it's up to the author to take it into account or not.

**Comment by pejakm** [comment]
Okay, I just figured out: although `app_name` is marked untranslatable, the app is still translated if the string is present in strings.xml. So everything should be okay if you accept this PR. :)

**Comment by casimir** [comment]
Thanks for the details on how you localize in Serbian. I'm all for following the rules. Therefore ```app_name``` is now translatable. I also added the Play Store description in [this folder](https://github.com/casimir/simpleDeadlines/tree/master/store/description), feel free to add your translation.

I just figure I didn't even thank you. So thanks a lot. For the translation and for the information on the Serbian way.

**Comment by pejakm** [comment]
Thank you very much! :)

**Comment by pejakm** [comment]
Are there any problems with this, is it going to be merged? Just wondering in case I need to update it or something. :)

**Comment by casimir** [comment]
:+1:

**Comment by pejakm** [comment]
Thanks!

**Pull request merged**
